default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") {5} %>
  username: postgres
  password: password
  host: localhost

development:
  <<: *default
  database: greatest-games_development

test: 
  <<: *default
  database: greatest-games_test

production:
  <<: *default
  database: greatest-games_production
    # username: greatest-games
    # password: <%= ENV['greatest-games_DATABASE_PASSWORD'] %>